### ISSUE TITLE
Eclipse show many Bugs! 

### ISSUE THREAD

**Issue by Leandros** [Dawnthorn/nagare#2]
Hey, 

I imported Nagare to Eclipse and want to try it on my device (Samsung Galaxy S GT-I9000 / Android 2.2), but there are some bugs. 
(Screenshot: http://yfrog.com/9fbugsksj)

Can you help me?!

Thanks!

**Comment by cynicaljoy** [comment]
You need to delete the R.java and INagareService.java files from the src directory as these are supposed to be generated files.

**Comment by Leandros** [comment]
Now I get other error in "DownloadThread.Java" I hope I can solve this ;)

**Comment by Leandros** [comment]
Not closed!

**Comment by cynicaljoy** [comment]
can you do another screenshot? btw, this isn't actually a defect as much as it is the .gitignore file needing to be defined/updated by the maintainer.

**Comment by Leandros** [comment]
Now Eclipse show (after a restart) only a warning. Screen: http://www.abload.de/img/githubcg4a.jpg

**Comment by cynicaljoy** [comment]
That is just a warning, you can ignore it. You should be able to get the project to build without any problems now.

**Comment by Leandros** [comment]
I try it!

**Comment by Leandros** [comment]
Now I got an error in the android app ;) 

 java.lang.NumberFormatException: unable to parse "null" as integer

or 

java.io.FileNotFoundException: /sdcard/Nagare/The Radio CC-2011115204648.mp3 

(Tested with http://the-radio.cc:8000 as Stream URL)
Iam working on an app for the radio!

**Comment by Leandros** [comment]
App works now.

**Comment by Leandros** [comment]
Where can I edit the standard stream? In the field?

**Comment by cynicaljoy** [comment]
Sorry, but this isn't a forum for learning. I don't mean to be rude but it seems that you should begin by learning Java before you start attempting Android Development.

**Comment by Leandros** [comment]
;)
